// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: set.proto

//当前目录的包名

package protoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//Grodens 请求结构
type Grodens struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Grodens) Reset() {
	*x = Grodens{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Grodens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grodens) ProtoMessage() {}

func (x *Grodens) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grodens.ProtoReflect.Descriptor instead.
func (*Grodens) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{0}
}

func (x *Grodens) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

//Gou响应结构
type Gou struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mess string `protobuf:"bytes,1,opt,name=mess,proto3" json:"mess,omitempty"`
}

func (x *Gou) Reset() {
	*x = Gou{}
	if protoimpl.UnsafeEnabled {
		mi := &file_set_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Gou) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gou) ProtoMessage() {}

func (x *Gou) ProtoReflect() protoreflect.Message {
	mi := &file_set_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gou.ProtoReflect.Descriptor instead.
func (*Gou) Descriptor() ([]byte, []int) {
	return file_set_proto_rawDescGZIP(), []int{1}
}

func (x *Gou) GetMess() string {
	if x != nil {
		return x.Mess
	}
	return ""
}

var File_set_proto protoreflect.FileDescriptor

var file_set_proto_rawDesc = []byte{
	0x0a, 0x09, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69,
	0x6e, 0x22, 0x1d, 0x0a, 0x07, 0x47, 0x72, 0x6f, 0x64, 0x65, 0x6e, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x19, 0x0a, 0x03, 0x47, 0x6f, 0x75, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x65, 0x73, 0x73, 0x32, 0x2b, 0x0a, 0x06, 0x50,
	0x72, 0x6f, 0x64, 0x65, 0x6e, 0x12, 0x21, 0x0a, 0x03, 0x61, 0x64, 0x64, 0x12, 0x0d, 0x2e, 0x6d,
	0x61, 0x69, 0x6e, 0x2e, 0x47, 0x72, 0x6f, 0x64, 0x65, 0x6e, 0x73, 0x1a, 0x09, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x47, 0x6f, 0x75, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_set_proto_rawDescOnce sync.Once
	file_set_proto_rawDescData = file_set_proto_rawDesc
)

func file_set_proto_rawDescGZIP() []byte {
	file_set_proto_rawDescOnce.Do(func() {
		file_set_proto_rawDescData = protoimpl.X.CompressGZIP(file_set_proto_rawDescData)
	})
	return file_set_proto_rawDescData
}

var file_set_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_set_proto_goTypes = []interface{}{
	(*Grodens)(nil), // 0: main.Grodens
	(*Gou)(nil),     // 1: main.Gou
}
var file_set_proto_depIdxs = []int32{
	0, // 0: main.Proden.add:input_type -> main.Grodens
	1, // 1: main.Proden.add:output_type -> main.Gou
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_set_proto_init() }
func file_set_proto_init() {
	if File_set_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_set_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Grodens); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_set_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Gou); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_set_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_set_proto_goTypes,
		DependencyIndexes: file_set_proto_depIdxs,
		MessageInfos:      file_set_proto_msgTypes,
	}.Build()
	File_set_proto = out.File
	file_set_proto_rawDesc = nil
	file_set_proto_goTypes = nil
	file_set_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProdenClient is the client API for Proden service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProdenClient interface {
	//添加rpc接口
	//定义add方法
	Add(ctx context.Context, in *Grodens, opts ...grpc.CallOption) (*Gou, error)
}

type prodenClient struct {
	cc grpc.ClientConnInterface
}

func NewProdenClient(cc grpc.ClientConnInterface) ProdenClient {
	return &prodenClient{cc}
}

func (c *prodenClient) Add(ctx context.Context, in *Grodens, opts ...grpc.CallOption) (*Gou, error) {
	out := new(Gou)
	err := c.cc.Invoke(ctx, "/main.Proden/add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProdenServer is the server API for Proden service.
type ProdenServer interface {
	//添加rpc接口
	//定义add方法
	Add(context.Context, *Grodens) (*Gou, error)
}

// UnimplementedProdenServer can be embedded to have forward compatible implementations.
type UnimplementedProdenServer struct {
}

func (*UnimplementedProdenServer) Add(context.Context, *Grodens) (*Gou, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterProdenServer(s *grpc.Server, srv ProdenServer) {
	s.RegisterService(&_Proden_serviceDesc, srv)
}

func _Proden_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Grodens)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProdenServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Proden/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProdenServer).Add(ctx, req.(*Grodens))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proden_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Proden",
	HandlerType: (*ProdenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "add",
			Handler:    _Proden_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "set.proto",
}
