name: StarYuhen

# https://search.maven.org/artifact/mysql/mysql-connector-java 使用这个网站来搜索库

# 自定义的字段
database:
    user: root
    password: abc123456


# 音容spring的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eim
    username: root
    password: abc123456
    # 引用driver数据库类
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema.sql
# 禁止使用h2
    # driver-class-name: com.mysql.jdbc.Driver
    # druid 配置 https://github.com/alibaba/druid/blob/master/druid-spring-boot-starter/README.md
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 配置监控页功能
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin
        resetEnable: false
       # 监控web
      web-stat-filter:
        enabled: true
        urlPattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          logSlowSql: true
          enabled: true
        wall:
          enabled: true
          config:
          drop-table-allow: false
#  sql:
#    init:
#      schmea-locations: classpath:db/schema.sql
#      data-locations: classpath:db/UserData.sql
