// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package protoc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求这个微服务方法内容
type TestHello struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestHello) Reset()         { *m = TestHello{} }
func (m *TestHello) String() string { return proto.CompactTextString(m) }
func (*TestHello) ProtoMessage()    {}
func (*TestHello) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *TestHello) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestHello.Unmarshal(m, b)
}
func (m *TestHello) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestHello.Marshal(b, m, deterministic)
}
func (m *TestHello) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestHello.Merge(m, src)
}
func (m *TestHello) XXX_Size() int {
	return xxx_messageInfo_TestHello.Size(m)
}
func (m *TestHello) XXX_DiscardUnknown() {
	xxx_messageInfo_TestHello.DiscardUnknown(m)
}

var xxx_messageInfo_TestHello proto.InternalMessageInfo

func (m *TestHello) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 响应消息
type TestReturn struct {
	Return               string   `protobuf:"bytes,1,opt,name=Return,proto3" json:"Return,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestReturn) Reset()         { *m = TestReturn{} }
func (m *TestReturn) String() string { return proto.CompactTextString(m) }
func (*TestReturn) ProtoMessage()    {}
func (*TestReturn) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *TestReturn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestReturn.Unmarshal(m, b)
}
func (m *TestReturn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestReturn.Marshal(b, m, deterministic)
}
func (m *TestReturn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestReturn.Merge(m, src)
}
func (m *TestReturn) XXX_Size() int {
	return xxx_messageInfo_TestReturn.Size(m)
}
func (m *TestReturn) XXX_DiscardUnknown() {
	xxx_messageInfo_TestReturn.DiscardUnknown(m)
}

var xxx_messageInfo_TestReturn proto.InternalMessageInfo

func (m *TestReturn) GetReturn() string {
	if m != nil {
		return m.Return
	}
	return ""
}

func init() {
	proto.RegisterType((*TestHello)(nil), "test.TestHello")
	proto.RegisterType((*TestReturn)(nil), "test.TestReturn")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xe4, 0xb9, 0x38, 0x43, 0x52,
	0x8b, 0x4b, 0x3c, 0x52, 0x73, 0x72, 0xf2, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25, 0x15, 0x2e, 0x2e, 0x90, 0x82, 0xa0, 0xd4,
	0x92, 0xd2, 0xa2, 0x3c, 0x21, 0x31, 0x2e, 0x36, 0x08, 0x0b, 0xaa, 0x06, 0xca, 0x33, 0x32, 0xe1,
	0x62, 0x01, 0xa9, 0x12, 0xd2, 0xe1, 0x62, 0x85, 0x18, 0xc5, 0xaf, 0x07, 0xb6, 0x0a, 0x6e, 0xb6,
	0x94, 0x00, 0x42, 0x00, 0xa2, 0x47, 0x89, 0xc1, 0x89, 0x33, 0x8a, 0x5d, 0x1f, 0xec, 0x98, 0xe4,
	0x24, 0x36, 0x30, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf8, 0x28, 0xc4, 0x59, 0xa2, 0x00,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TestClient is the client API for Test service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TestClient interface {
	// 定义一个hello方法
	Hello(ctx context.Context, in *TestHello, opts ...grpc.CallOption) (*TestReturn, error)
}

type testClient struct {
	cc *grpc.ClientConn
}

func NewTestClient(cc *grpc.ClientConn) TestClient {
	return &testClient{cc}
}

func (c *testClient) Hello(ctx context.Context, in *TestHello, opts ...grpc.CallOption) (*TestReturn, error) {
	out := new(TestReturn)
	err := c.cc.Invoke(ctx, "/test.Test/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestServer is the server API for Test service.
type TestServer interface {
	// 定义一个hello方法
	Hello(context.Context, *TestHello) (*TestReturn, error)
}

// UnimplementedTestServer can be embedded to have forward compatible implementations.
type UnimplementedTestServer struct {
}

func (*UnimplementedTestServer) Hello(ctx context.Context, req *TestHello) (*TestReturn, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}

func RegisterTestServer(s *grpc.Server, srv TestServer) {
	s.RegisterService(&_Test_serviceDesc, srv)
}

func _Test_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestHello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test.Test/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServer).Hello(ctx, req.(*TestHello))
	}
	return interceptor(ctx, in, info, handler)
}

var _Test_serviceDesc = grpc.ServiceDesc{
	ServiceName: "test.Test",
	HandlerType: (*TestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Test_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
